const express = require("express")
const cors = require("cors")
require("dotenv").config()
const router = require("./route/index")
require("./config/database")

const app = express()
app.use(express.static("public"))
app.use(cors())
app.use(express.json())
app.set("view engine", "ejs")
app.use(express.urlencoded({extended: true}))
app.use("/", router)
app.listen(4000, () => console.log("server listening on port 4000"))